[package]
name = "dw-wdt"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Portable Synopsys DesignWare watchdog timer driver"
keywords = ["os", "driver", "watchdog"]
categories = ["embedded", "no-std"]

[dependencies]
mmio-api.workspace = true
thiserror.workspace = true
